// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4PYApHS-hf9kQA30aw-kXwTDlO760-Do',
    appId: '1:319846104234:web:19931abe83d2667ac4a4d3',
    messagingSenderId: '319846104234',
    projectId: 'pascal-iot',
    authDomain: 'pascal-iot.firebaseapp.com',
    storageBucket: 'pascal-iot.firebasestorage.app',
    measurementId: 'G-FSTMXJV4CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBs1Zz7VYKl32LUXbZILe4J7ccvmonguU',
    appId: '1:319846104234:android:29a2d5a4447d6a4ec4a4d3',
    messagingSenderId: '319846104234',
    projectId: 'pascal-iot',
    storageBucket: 'pascal-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlkZddy60Gl_wKn4XVZs74CXa6xaX3iZQ',
    appId: '1:319846104234:ios:d700a64154b9e7c3c4a4d3',
    messagingSenderId: '319846104234',
    projectId: 'pascal-iot',
    storageBucket: 'pascal-iot.firebasestorage.app',
    iosBundleId: 'com.example.pascolMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlkZddy60Gl_wKn4XVZs74CXa6xaX3iZQ',
    appId: '1:319846104234:ios:d700a64154b9e7c3c4a4d3',
    messagingSenderId: '319846104234',
    projectId: 'pascal-iot',
    storageBucket: 'pascal-iot.firebasestorage.app',
    iosBundleId: 'com.example.pascolMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4PYApHS-hf9kQA30aw-kXwTDlO760-Do',
    appId: '1:319846104234:web:c78d0153aa22737bc4a4d3',
    messagingSenderId: '319846104234',
    projectId: 'pascal-iot',
    authDomain: 'pascal-iot.firebaseapp.com',
    storageBucket: 'pascal-iot.firebasestorage.app',
    measurementId: 'G-3M8JCLRKBJ',
  );
}
